global:
  message: Welcome to customer service dev inv!!
server:
  port: 8082
message: hello this is from Dev
spring:
  datasource:
    url: jdbc://mysql://localhost:3306/cust_dev
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: Imdisaster@1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
