global:
  message: Welcome to customer service prod inv!!
server:
  port: 8083
message: hello this is from prod
spring:
  datasource:
    url: jdbc://mysql://localhost:3306/cust_prod
    username: root
    password: Imdisaster@1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
