global:
  message: Welcome to order service prod inv!!
server:
  port: 8085
message: hello this is from prod
spring:
  datasource:
    url: jdbc://mysql://localhost:3306/order_prod
    username: root
    password: Imdisaster@1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
